version: "3"
services:
  safyclient:
    image: safyclient
    restart: always
    ports:
      - "1002:80"
    build:
      context: client
    networks:
      - safynetwork
  safyapi:
    image: safyapi
    restart: always
    ports:
      - "1001:1001"
    build:
      context: server
      dockerfile: ./src/api/Dockerfile
    depends_on:
      - safystore
    networks:
      - safynetwork
  safystore:
    image: safystore
    restart: always
    build:
      context: db
    ports:
      - "3311:3306"
    networks:
      - safynetwork
networks:
  safynetwork:
    driver: bridge